"""Phase 1 pipeline -- data loading & validation.

Runs the loader and the validator on the raw CSV, writes the machine-readable
summary (JSON), the column and missingness tables (CSV), and a human-readable
audit report (Markdown). Deterministic and read-only with respect to the raw
data.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data_loader import load_raw_csv  # noqa: E402
from src.data_validator import flatten_profile, validate_dataset  # noqa: E402

CONFIG_RELATIVE = "configs/phase1_config.json"
RAW_RELATIVE = "data/raw/elderly_data.csv"
OUTPUT_DIR = "outputs/phase1_data_validation"
REPORT_RELATIVE = "reports/phase1_data_validation_report.md"


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def load_config(root: Path) -> Dict[str, Any]:
    with open(root / CONFIG_RELATIVE, encoding="utf-8") as handle:
        return json.load(handle)


def _md_table(headers: List[str], rows: List[List[str]]) -> str:
    if not rows:
        return f"| {' | '.join(headers)} |\n|{'---|' * len(headers)}\n_(none)_\n"
    lines = [f"| {' | '.join(headers)} |", f"|{'---|' * len(headers)}"]
    for row in rows:
        lines.append(f"| {' | '.join(str(c) for c in row)} |")
    return "\n".join(lines) + "\n"


def _render_report(summary: Dict[str, Any], config: Dict[str, Any]) -> str:
    file_level = summary["file_level"]
    dataset = summary["dataset_level"]
    missingness = summary["missingness"]
    duplicates = summary["duplicates"]
    identifier = summary["identifier"]
    target = summary["target"]
    profiles = summary["column_profiles"]
    all_empty = summary["all_empty_columns"]
    issues = summary["column_name_issues"]
    warnings = summary["warnings"]
    ambiguities = summary["ambiguities"]

    lines: List[str] = []
    lines.append("# Phase 1 -- Data Loading & Validation Report")
    lines.append("")
    lines.append("Generated by `src/phase1_data_validation.py`. The raw CSV is treated as immutable; nothing in this phase modifies it.")
    lines.append("")

    lines.append("## Dataset")
    lines.append("")
    lines.append(f"- **Path:** `{file_level['path']}`")
    lines.append(f"- **Participants (rows):** {dataset['n_rows']}")
    lines.append(f"- **Variables (columns):** {dataset['n_columns']}")
    lines.append(f"- **Encoding:** {file_level['encoding']} (BOM: {file_level['bom_present']})")
    lines.append(f"- **Newline style:** {file_level['newline_style']}")
    lines.append(f"- **Size:** {file_level['size_bytes']} bytes, {file_level['n_lines']} lines")
    lines.append(f"- **MD5:** {file_level['md5']}")
    lines.append(f"- **SHA-256:** {file_level['sha256']}")
    lines.append("")

    lines.append("## File-level checks")
    lines.append("")
    lines.append(
        _md_table(
            ["Check", "Result"],
            [[c["check"], "PASS" if c["passed"] else "FAIL"] for c in file_level["checks"]],
        )
    )
    lines.append("")

    lines.append("## Dataset-level checks")
    lines.append("")
    lines.append(
        _md_table(
            ["Property", "Expected", "Observed", "Status"],
            [
                ["Rows", dataset["expected_rows"], dataset["n_rows"], "PASS" if dataset["rows_match_config"] else "FAIL"],
                ["Columns", dataset["expected_columns"], dataset["n_columns"], "PASS" if dataset["columns_match_config"] else "FAIL"],
                ["Identifier column present", "Yes", str(dataset["required_columns_present"][config["columns"]["identifier"]["column"]]), "PASS" if dataset["required_columns_present"][config["columns"]["identifier"]["column"]] else "FAIL"],
                ["Target column present", "Yes", str(dataset["required_columns_present"][config["columns"]["target"]["column"]]), "PASS" if dataset["required_columns_present"][config["columns"]["target"]["column"]] else "FAIL"],
            ],
        )
    )
    lines.append("")
    lines.append("### Column names (verbatim)")
    lines.append("")
    lines.append("`" + "`, `".join(dataset["column_names"]) + "`")
    lines.append("")

    lines.append("## Duplicates")
    lines.append("")
    dup_rows = duplicates["complete_duplicate_rows"]
    lines.append(
        _md_table(
            ["Check", "Method", "Result"],
            [
                ["Duplicate complete rows", dup_rows.get("method", "-"), f"{dup_rows.get('n_rows_flagged', 0)} first-flagged, {dup_rows.get('n_rows_involved', 0)} involved"],
                ["Duplicate participant IDs", "duplicated Participant_ID", f"{duplicates['duplicate_participant_ids'].get('n_duplicates', 0)}"],
                ["Identical measurement rows across different IDs", "duplicated measurement columns", f"{duplicates['cross_cohort_identical_measurement_rows']}"],
            ],
        )
    )
    shared = duplicates.get("shared_numeric_id_suffixes", [])
    lines.append("")
    lines.append(f"**Shared numeric ID suffixes (observation):** {len(shared)} suffixes appear in both cohorts (e.g. CO-001 and FL-001). {duplicates.get('shared_suffix_note', '')}")
    lines.append("")

    lines.append("## Identifier audit")
    lines.append("")
    pref_counts = "".join(
        f"; {k}: {v}" for k, v in sorted(identifier.get("prefix_counts", {}).items())
    )
    lines.append(
        _md_table(
            ["Property", "Value"],
            [
                ["Column", identifier.get("column", "-")],
                ["Rows / unique IDs", f"{identifier.get('n_rows', '-')} / {identifier.get('n_unique', '-')}"],
                ["Missing IDs", identifier.get("n_missing", "-")],
                ["Duplicate IDs", identifier.get("n_duplicates", "-")],
                ["Format regex", str(identifier.get("format_regex", "-"))],
                ["All IDs match format", "Yes" if identifier.get("all_match_format") else "No"],
                ["Prefix counts (CO/FL)" if pref_counts == "" else "Prefix counts", pref_counts.lstrip("; ")],
                ["Sample IDs", ", ".join(identifier.get("sample_ids", []))],
            ],
        )
    )
    lines.append("")

    lines.append("## Target audit (`HighFallRisk`)")
    lines.append("")
    if target:
        alignment = target.get("cohort_alignment", {})
        diff = target.get("class_counts_difference")
        diff_txt = "none" if diff is None else str(diff)
        lines.append(
            _md_table(
                ["Property", "Value"],
                [
                    ["Column", target["column"]],
                    ["Missing values", target["n_missing"]],
                    ["Classes", ", ".join(str(v) for v in target["values"])],
                    ["Binary", "Yes" if target["is_binary"] else "No"],
                    ["Class counts", str(target["class_counts"])],
                    ["Expected class counts", str(target.get("expected_class_counts", "-"))],
                    ["Class-count difference vs config", diff_txt],
                    ["Unexpected values", str(target["unexpected_values"])],
                    ["Cohort-alignment hypothesis (CO->0, FL->1)", f"aligned={alignment.get('n_aligned')}/{alignment.get('n_checked')}"],
                ],
            )
        )
    lines.append("")
    lines.append("Target is treated as the cohort label pending source verification (see ambiguities).")
    lines.append("")

    lines.append("## All-empty columns")
    lines.append("")
    lines.append(f"{len(all_empty)} columns are completely missing:")
    lines.append("")
    lines.append("`" + "`, `".join(all_empty) + "`")
    lines.append("")
    lines.append("They are reported and **not** removed, imputed, or fabricated in this phase.")
    lines.append("")

    lines.append("## Missingness")
    lines.append("")
    rep = missingness["representations"]
    rep_txt = f"only empty cells (`\"\"`); no literal NA tokens" if "literal_tokens" not in rep else str(rep)
    lines.append(
        f"- **Representations found in raw cells:** empty_string={rep.get('empty_string', 0)}, "
        f"whitespace_only={rep.get('whitespace_only', 0)}"
        + (f", literal_tokens={rep['literal_tokens']}" if "literal_tokens" in rep else "")
    )
    lines.append(f"- Overall: {missingness['n_missing_cells']} / {missingness['n_total_cells']} cells missing ({missingness['overall_missing_pct']}%).")
    lines.append("")
    lines.append(
        _md_table(
            ["Column", "Non-missing", "Missing", "Missing %"],
            [[r["column"], r["n_nonnull"], r["n_missing"], f"{r['missing_pct']}%"] for r in missingness["table"]],
        )
    )
    lines.append("")

    lines.append("## Column profiles (data types)")
    lines.append("")
    lines.append(
        _md_table(
            ["Column", "Inferred type", "Non-null", "Missing", "Missing %", "Unique", "Examples"],
            [
                [
                    p["column"],
                    p["inferred_type"],
                    p["n_nonnull"],
                    p["n_missing"],
                    f"{p['missing_pct']}%",
                    p["n_unique"],
                    " | ".join(str(v) for v in p["example_values"]),
                ]
                for p in profiles
            ],
        )
    )
    lines.append("")

    numeric_rows = []
    for p in profiles:
        numeric = p.get("numeric")
        if numeric:
            numeric_rows.append(
                [
                    p["column"],
                    numeric["min"],
                    numeric["max"],
                    numeric["mean"],
                    numeric["median"],
                ]
            )
    lines.append("## Numeric descriptive statistics (reporting only)")
    lines.append("")
    lines.append(
        _md_table(
            ["Column", "Min", "Max", "Mean", "Median"],
            numeric_rows,
        )
    )
    lines.append("No outlier deletion, transformation, or scaling was applied.")
    lines.append("")

    categorical_rows = []
    for p in profiles:
        frequencies = p.get("value_frequencies")
        if frequencies:
            freq_txt = "; ".join(f"{k}: {v}" for k, v in frequencies.items())
            categorical_rows.append([p["column"], p["n_missing"], freq_txt])
    lines.append("## Categorical validation (value frequencies)")
    lines.append("")
    lines.append(
        _md_table(
            ["Column", "Missing count", "Values (value: count)"],
            categorical_rows,
        )
    )
    lines.append("")

    lines.append("## Encoding / column-name issues")
    lines.append("")
    lines.append(
        _md_table(
            ["Type", "Column(s)", "Note"],
            [
                [
                    i["type"],
                    i.get("column", ", ".join(i.get("columns", []))),
                    i.get("note", ""),
                ]
                for i in issues
            ],
        )
    )
    if issues:
        mapping = summary.get("column_name_mapping", {})
        lines.append("")
        lines.append("Internal-programming name mapping (original names preserved in all outputs):")
        for original, internal in mapping.items():
            lines.append(f"- `{original}` -> `{internal}`")
    lines.append("")

    lines.append("## Leakage flags (structural audit; no model trained)")
    lines.append("")
    lines.append(
        _md_table(
            ["Variable", "Status", "Note"],
            [
                [str(f["variable"] or "(entire dataset)"), f["status"], f["note"]]
                for f in summary["leakage_flags"]
            ],
        )
    )
    lines.append("")

    lines.append("## Warnings")
    lines.append("")
    if warnings:
        for w in warnings:
            lines.append(f"- {w}")
    else:
        lines.append("- None. Loaded data matches all configured structural expectations.")
    lines.append("")

    lines.append("## Unresolved ambiguities")
    lines.append("")
    for a in ambiguities:
        lines.append(f"- **{a['item']}:** {a['note']}")
    lines.append("")

    lines.append("## Critical checks")
    lines.append("")
    lines.append(f"**All critical structural checks passed:** {'YES' if summary['critical_checks_passed'] else 'NO'}")
    if summary["failures"]:
        for failure in summary["failures"]:
            lines.append(f"- FAIL: {failure}")
    lines.append("")
    lines.append("## Recommended next step")
    lines.append("")
    lines.append("**Phase 2:** statistical descriptive analysis and distribution checks (spec 5-6), per the project rules -- not started automatically.")
    lines.append("")
    return "\n".join(lines)


def _full_summary(meta: Dict[str, Any], validation: Dict[str, Any]) -> Dict[str, Any]:
    return {"phase": "phase1_data_validation", **validation}


def run_phase1(root: Path) -> Dict[str, Any]:
    """Load + validate the raw CSV and write all Phase 1 outputs."""
    root = Path(root)
    config = load_config(root)
    raw_abs = (root / config["dataset"]["raw_path"]).resolve()

    frame, meta = load_raw_csv(
        raw_abs,
        encoding=config["dataset"]["expected_encoding"],
        delimiter=config["dataset"]["expected_delimiter"],
    )
    meta["relative_path"] = config["dataset"]["raw_path"]

    validation = validate_dataset(frame, meta, config)
    summary = _full_summary(meta, validation)

    out_dir = root / OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    report_dir = root / REPORT_RELATIVE.rsplit("/", 1)[0]
    report_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "data_validation_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    pd.DataFrame([flatten_profile(p) for p in summary["column_profiles"]]).to_csv(
        out_dir / "column_profile.csv", index=False, encoding="utf-8"
    )

    pd.DataFrame(summary["missingness"]["table"]).to_csv(
        out_dir / "missingness.csv", index=False, encoding="utf-8"
    )

    (root / REPORT_RELATIVE).write_text(
        _render_report(summary, config), encoding="utf-8"
    )

    return {
        "summary": summary,
        "outputs": {
            "summary_json": str((out_dir / "data_validation_summary.json").as_posix()),
            "column_profile_csv": str((out_dir / "column_profile.csv").as_posix()),
            "missingness_csv": str((out_dir / "missingness.csv").as_posix()),
            "report_md": REPORT_RELATIVE,
        },
        "critical_checks_passed": summary["critical_checks_passed"],
    }


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass
    result = run_phase1(project_root())
    summary = result["summary"]
    print("Phase 1 data validation completed.")
    print(f"  Dataset : {summary['file_level']['path']}")
    print(f"  Shape   : {summary['dataset_level']['n_rows']} x {summary['dataset_level']['n_columns']}")
    print(f"  Missing : {summary['missingness']['n_missing_cells']} cells ({summary['missingness']['overall_missing_pct']}%)")
    print(f"  Empty cols: {len(summary['all_empty_columns'])}")
    print(f"  Duplicate rows: {summary['duplicates']['complete_duplicate_rows'].get('n_rows_involved', 0)}; duplicate IDs: {summary['duplicates']['duplicate_participant_ids'].get('n_duplicates', 0)}")
    print(f"  Target  : {summary['target']['class_counts']} (binary={summary['target']['is_binary']}, missing={summary['target']['n_missing']})")
    print(f"  Critical checks passed: {summary['critical_checks_passed']}")
    for key, path in result["outputs"].items():
        print(f"  wrote  : {path}")


if __name__ == "__main__":
    main()